#!/usr/bin/env node
"use strict";
const { execFileSync } = require("node:child_process");
const args = process.argv.slice(2);
try {
  execFileSync("tsc", args, { stdio: "inherit" });
} catch (err) {
  process.exit(err.status ?? 1);
}